apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: atmbhb793-nodejs 
  janus-idp.io/tekton: atmbhb793-nodejs
  backstage.io/kubernetes-id: atmbhb793-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: atmbhb793-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  